# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jctl < Formula
  desc "Jenkins Control Tool - CLI for Jenkins"
  homepage "https://github.com/robyt96/jctl"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Robyt96/jctl/releases/download/v0.1.0/jctl_0.1.0_darwin_amd64.tar.gz"
      sha256 "183396523115f773fac7dc875816ebc2c06116405127c46d1f46bcb6b4d4558b"

      def install
        bin.install "jctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Robyt96/jctl/releases/download/v0.1.0/jctl_0.1.0_darwin_arm64.tar.gz"
      sha256 "42a708b31ee7e24a440809165c00549faecf2a7ec55d4e8f0d18034f84c37d86"

      def install
        bin.install "jctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Robyt96/jctl/releases/download/v0.1.0/jctl_0.1.0_linux_amd64.tar.gz"
      sha256 "c5cc74e6fcd022584d24defd8bc58384a382558997f8bd0f5d1c9b7172a774e3"
      def install
        bin.install "jctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Robyt96/jctl/releases/download/v0.1.0/jctl_0.1.0_linux_arm64.tar.gz"
      sha256 "81a74384dbc37bf427ed03b50d9d605a0180d1264e47d413618ad644ac9a9826"
      def install
        bin.install "jctl"
      end
    end
  end

  test do
    system "#{bin}/jctl", "--version"
  end
end
